FROM nimmis/alpine-micro:3.6

ENV GLIBC_VERSION=2.26-r0

RUN apk update && apk upgrade && \

    # add extra package for installation  
    apk add curl && \

    # download packages for glibc, see https://github.com/sgerrand/alpine-pkg-glibc for more info
    curl -L -o glibc-${GLIBC_VERSION}.apk \
      "https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VERSION}/glibc-${GLIBC_VERSION}.apk" && \
    curl -L -o glibc-bin-${GLIBC_VERSION}.apk \
      "https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VERSION}/glibc-bin-${GLIBC_VERSION}.apk" && \

    # install them
    apk add --allow-untrusted glibc-${GLIBC_VERSION}.apk glibc-bin-${GLIBC_VERSION}.apk && \

    # download and upack golang
    curl https://storage.googleapis.com/golang/go1.9.1.linux-amd64.tar.gz | tar xzf - -C / && \
    mv /go /goroot && \
 
    # remove extra packages
    apk del curl && \

    # remove cached info
    rm -rf /var/cache/apk/*

ENV GOROOT=/goroot \
    GOPATH=/gopath \
    GOBIN=/gopath/bin \
    PATH=${PATH}:/goroot/bin:/gopath/bin
